### ISSUE TITLE
docs: how bluebuild works

### ISSUE THREAD

**Issue by xynydev** [blue-build/website#49]
https://blue-build.org/learn/how/

Outline the process of turning recipes into containerfiles, the repo structure, how the modules are launched and what they do, etc. 

Will need help from @gmpinder here at least. You got a good docs streak going with the #48 PR lol, so creating an issue for this now.

**Comment by xynydev** [comment]
I figured that an example recipe would be a great way to start this, so here's a sketch. The comments are WIP and won't stay like that.

```yaml
# example-recipe.yml

# metadata
name: turquoise
description: An example recipe for explaining how BlueBuild works.

# base image
base-image: ghcr.io/ublue-os/silverblue-main
image-version: latest

# stages, to explain all that
stages:
  - name: helix
    from: docker.io/library/rust
    modules:
      - type: script
        snippets:
          - apt-get update && apt-get install -y git # Install git
          - git clone https://github.com/helix-editor/helix.git # Clone the helix repo
          - cd helix && RUSTFLAGS="-C target-feature=-crt-static" cargo install --path helix-term # Use cargo to install
          - mkdir -p /out/ && mv $CARGO_HOME/bin/hx /out/hx && mv runtime /out/ # Move bin and runtime

modules:
  # helix stage copy
  - type: copy
    from: helix
    src: /out/hx
    dest: /usr/bin/
  - type: copy
    from: helix
    src: /out/runtime
    dest: /usr/lib64/helix/
	
  - type: files
    files:
       - usr: /usr # need to do the files-related changes because i don't wanna be stuck explaining this

  # classic module of the build-time-only variety
  - type: rpm-ostree
    repos:
       - https://copr.fedorainfracloud.org/coprs/atim/starship/repo/fedora-%OS_VERSION%/atim-starship-fedora-%OS_VERSION%.repo
     install:
        - fish
        - starship

  # classic module of the post-boot variety
  - type: default-flatpaks
    user:
        install:
            - org.kde.krita
            - org.blender.Blender
            - org.gnome.World.PikaBackup


```
